inherit_gem:
  rubocop-lts: config/rubygem_rspec.yml

inherit_from:
  - .rubocop_rspec.yml

plugins: rubocop-on-rbs

# This tells RuboCop to add the exclusions in this file
# to the default exclusions (and those from other inherited files),
# rather than overwriting them.
inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - certs/**/*
    - checksums/**/*
    - docs/**/*
    - examples/**/*
    - fixtures/**/*
    - gemfiles/*.gemfile
    - pkg/**/*
    - results/**/*
    - spec/fixtures/**/*
    - tmp/**/*
    - vendor/**/*
    - AGENTS.md

RBS:
  Enabled: true

Layout/IndentationConsistency:
  Exclude: ['*.md']
